'use client';

import { useEffect, useState } from 'react';
import type { CareAccessMetrics } from '@/lib/careAccess/types';

export default function AdminCareAccessPage() {
  const [metrics, setMetrics] = useState<CareAccessMetrics | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetch('/api/admin/care-access/metrics').then((r) => r.json()).then((j) => { if (!j.ok) setError(j.error?.message ?? 'Access denied.'); else setMetrics(j.data.metrics); }).catch(() => setError('Could not load care-access metrics.')); }, []);
  return <div className="space-y-5 py-2"><header><p className="fc-eyebrow">FlowCare operations</p><h1 className="mt-1 text-2xl font-extrabold text-ink-900">Care Access Exchange metrics</h1><p className="mt-1 max-w-2xl text-sm text-ink-600">Network-level workflow metrics. No patient clinical content is displayed here.</p></header>{error && <div className="fc-card p-6 text-sm font-semibold text-rose-800">{error}</div>}{metrics && <><section className="grid gap-3 sm:grid-cols-3 lg:grid-cols-4">{[['Care requests', metrics.total], ['Closed', metrics.closed], ['Closure rate', metrics.closureRate == null ? 'Not enough data' : `${metrics.closureRate}%`], ['Unresolved', metrics.unresolved], ['Pending approvals', metrics.pendingApprovals ?? 0], ['Waitlisted', metrics.waitlisted ?? 0], ['Recovery required', metrics.recoveryRequired ?? 0], ['Follow-up open', metrics.followUpsOpen]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-ink-200 bg-white p-4"><p className="text-[11px] font-semibold uppercase tracking-wide text-ink-500">{label}</p><p className="mt-1 text-2xl font-extrabold text-ink-900">{value}</p></div>)}</section><section className="fc-card p-5"><h2 className="text-base font-bold">Operational health</h2><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><Metric label="Avg acknowledgement" value={metrics.averageAcknowledgementMinutes == null ? 'Not enough data' : `${metrics.averageAcknowledgementMinutes} min`} /><Metric label="Avg booking" value={metrics.averageBookingMinutes == null ? 'Not enough data' : `${metrics.averageBookingMinutes} min`} /><Metric label="Stale capacity" value={metrics.staleCapacitySignals} /><Metric label="No-show" value={metrics.noShows} /></dl></section></>}</div>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg bg-ink-50 p-3"><dt className="text-xs text-ink-500">{label}</dt><dd className="mt-1 font-bold text-ink-900">{value}</dd></div>; }
